name       : babl
version    : 0.1.54
release    : 18
source     :
    - https://download.gimp.org/pub/babl/0.1/babl-0.1.54.tar.bz2 : 4d2bf1345d7214b08762e6d1e23d0038508b806dbf7c4c44386faee434682a07
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : babl is a dynamic, any to any, pixel format translation library
description: |
    It allows converting between different methods of storing pixels known as pixel formats that have with different bitdepths and other data representations, color models and component permutations.
    A vocabulary to formulate new pixel formats from existing primitives is provided as well as the framework to add new color models and data types.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
