name       : babl
version    : 0.1.46
release    : 14
source     :
    - https://download.gimp.org/pub/babl/0.1/babl-0.1.46.tar.bz2 : bbc2403b1badf8014ec42200e65d7b1f46e68e627c33c6242fa31ac5dc869e5b
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : babl is a dynamic, any to any, pixel format translation library.
description: |
    It allows converting between different methods of storing pixels known as pixel formats that have with different bitdepths and other data representations, color models and component permutations.
    A vocabulary to formulate new pixel formats from existing primitives is provided as well as the framework to add new color models and data types.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
