name       : babl
version    : 0.1.66
release    : 25
source     :
    - https://gitlab.gnome.org/GNOME/babl/-/archive/BABL_0_1_66/babl-BABL_0_1_66.tar.bz2 : de6e4c01c6ce4de572c67f3d8bf4a89fad7b304cda15ce394eeab7e22f30fc9c
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : babl is a dynamic, any to any, pixel format translation library
description: |
    It allows converting between different methods of storing pixels known as pixel formats that have with different bitdepths and other data representations, color models and component permutations.
    A vocabulary to formulate new pixel formats from existing primitives is provided as well as the framework to add new color models and data types.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
