name       : babl
version    : 0.1.48
release    : 15
source     :
    - https://download.gimp.org/pub/babl/0.1/babl-0.1.48.tar.bz2 : be9bd05cf55c8e46609ac1a30b1f63fe3917e0d7643c4d8d2798b68f3f752615
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : babl is a dynamic, any to any, pixel format translation library.
description: |
    It allows converting between different methods of storing pixels known as pixel formats that have with different bitdepths and other data representations, color models and component permutations.
    A vocabulary to formulate new pixel formats from existing primitives is provided as well as the framework to add new color models and data types.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
